language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jhh@easedot.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: hOkb26m97Po0JCJh6UbV021fdhqnBj3disDEkiGYAJqRkaGKsjUA0H4zGig+jnmLvNBMBR+HURkoMfj9SfxeEWmVNq1/m+PqwzS/zcdS+2YjCfqXrxWLkL15qH68hgVCa1Fq5CYfNVnjA6mjMjkkIFRuCASaBFGa6vMi2wkXJJG0aj7M6+ZkIotXQTLrQ3VKeic6xezUQ52e2NzsSDb3H70fz2CzH/7EYdgvJdPVXRsVfAmh3WVCrjjKdoSJwYI0htLHJlRXww3c0ZdaLGig8ZaoqXxJ1NCCwSf9Xhyw5ZWiKMGLILhCXWYyY67ddEWjj6SHCwgpVqc94tljnVzuyclE8qWfloGwJy/6DwvKDTQc/bJLhaFValwakTl4coA+Vrlr0TjXel2T7CayTyAGA2ieesKpD8ovjRJ42IF9zo8sBaXxWXRlU1k707tBRNhxf/cdA4NCt6P8HrZJ7O6oRZHWHoYPE/kURnbo92oca3LJQBOYTICaqXaCxcGUOykO1C5gnLqG8c3osFGvFYDQpkjSu0ot3UadykykNSEDGYEp3vHe9kE6pFidZF36e+BZXnnumaYY6DuKkIGMbZ2dLUFZdYUJMddgX1+aAP/Hem+phhYnNiZQg6htIGOGHxApR2MY/f3tRWFT9sBV827b4fxhlvDK6gQzuml9wq5Zs0I=
  - secure: Wa4nAUFLAbZaY5eWD7Ycb+A7Y5Ru8eMKAGgYrpxbBgSCr0QJSP2iftbYAwJSCzOv3ZjKbjz7IM5ukU6iUMpPtyTmKBpqTPibdl+z8PThaPlaGdaWcudmdRyIPds12ZtZLUngpZji4lnZCPvZhQju+LqjJ6BQszxjnXBd2m80zuRn6mBpPeiFvkB1AIefSpPmmGIbNAdaWBw3GzkaL4NLMPPneoB8cRiX17qk9hIEdh/GPtd2bG3w29XWO1dSc9VcGbWg4vlaqXF+Q8d/ooXUtyfXZ+AVk3HNOxBhAAH8/SENGx+oDNiBoCrRTt14WDJBr5V3XU3E3YFAat2AaRC3apkAkLQRptvr0acSBcBfCCFRLYDWI79LqFF+CJGfxpp5kRNERDo/Ti049jMyV2rjv9LdhDjKZfcM9jI/Or2rq/0j41q7+nSL8W3Q4T83y1rz/Pvy9IZTsfWuEpgx+8oOuhemDm0x4M2FzdSWz8QjmEBqzZ6JGVqb3oAR8YQqdx7xSbLa/5wLZ+X25iBkKFPc8sMpxbSMSCrdqlZ6ZIlkQ/rFVnHZ+7UK5Ves6VSfrcTGkjnNOAEjDka5Rs6XIo0Ot8zOJ1NGK6ceBAfLyUxNd6cElU0Xez1MU7M1XdgM36qJBhDXR5+w5jg2ecXKgTexg3cYZvmFTv4GgsHxO2/OW4o=
  - secure: m+2k/DgGaL3bM8UWuUF5RDN2Mbfaw7tD523T5MbxdssHXJ2rX/n2DMoAbSOTwJsBoPPYqfpCoihV3D8tG2yg6foSPl4X+/GUEPi73vQhC5zL3BDX99GTUXoXx8PgxW8hG+eMwGsguBju7bJP12lGwwivvOQCCz4VtE88H7TTyexMSyZo4vIaJT98Uver9UUHWhYmnaaztdEqEmYZ0TQorxUZAkIrW4a1E4Xz+a5GrIFWZNJLXux7nYnzC6yjmnzSg98e5Ku+atHDxGrd0LRXtuva8ZNgfNKUPva3iiS1AqUDHpxnqvnox1yeXp45kCc+uKAW7Ag/B3Vvh9KOYzJEdAgln3V1z3bsdG+G4tLmPvh77KSHeRxz+K7fJEB2gZjJFnJDh9hcxNesyQhBbcEaxArCcOv2iHVkQijwMMP0tyUtgeDlYkr0C9Z3J71i6mxIZ49aqOXvOZuFcXo386yIXWDsSLdwXy+uM8wgHVY97bIuvXbI0Hqy3ce6B8M8n3TYkPlf6481mU19keovbkR4dtOmfqi1qPCLqf+EV1cOg4E/3dotSMspZKjCYPcpL73gjEvcC1n/uwdnbRnU6yWBKi4YWqcectIyN0S2K9TPEmKpyVsrKznwiTQCqI+MQHCTYnimqvgx0CcmER35wIczKS4UQ9L/WI1b2ddFeWNwpTw=
before_install:
- gem install travis -v 1.8.5 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=34.209.148.131
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
