language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jhh@easedot.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: hOkb26m97Po0JCJh6UbV021fdhqnBj3disDEkiGYAJqRkaGKsjUA0H4zGig+jnmLvNBMBR+HURkoMfj9SfxeEWmVNq1/m+PqwzS/zcdS+2YjCfqXrxWLkL15qH68hgVCa1Fq5CYfNVnjA6mjMjkkIFRuCASaBFGa6vMi2wkXJJG0aj7M6+ZkIotXQTLrQ3VKeic6xezUQ52e2NzsSDb3H70fz2CzH/7EYdgvJdPVXRsVfAmh3WVCrjjKdoSJwYI0htLHJlRXww3c0ZdaLGig8ZaoqXxJ1NCCwSf9Xhyw5ZWiKMGLILhCXWYyY67ddEWjj6SHCwgpVqc94tljnVzuyclE8qWfloGwJy/6DwvKDTQc/bJLhaFValwakTl4coA+Vrlr0TjXel2T7CayTyAGA2ieesKpD8ovjRJ42IF9zo8sBaXxWXRlU1k707tBRNhxf/cdA4NCt6P8HrZJ7O6oRZHWHoYPE/kURnbo92oca3LJQBOYTICaqXaCxcGUOykO1C5gnLqG8c3osFGvFYDQpkjSu0ot3UadykykNSEDGYEp3vHe9kE6pFidZF36e+BZXnnumaYY6DuKkIGMbZ2dLUFZdYUJMddgX1+aAP/Hem+phhYnNiZQg6htIGOGHxApR2MY/f3tRWFT9sBV827b4fxhlvDK6gQzuml9wq5Zs0I=
  - secure: PM6H/+tJF/NVpXs71W9L8YPbSKlt6sE9e9OO2a0T4MqE5YIXunkQYgaS/6GrCGOZK5do41Y+bBaf4tJz/2mNtqkBd7nzLBlm64On+N+yRMM32z66UtCgVgWqKvfi8YFAygnxZlWlfDkCRU7lqy544kdxy3xv0mwKdfBNl1sPRfr7/V9QzItZI++ymjhiCWkip13e5gawcFtx10JVnIcIdttwihz1Yrl5090nGeJfWfVKQ20pgULB54W21QmU5y4a9n/TG/xBqAg+k0DQCEAomI1IflfhSRDuDiX+ibwX2BZu1I6MzPfwJqTp+uMnEJJcjJB996gs4JB59HUkwHa3nfcg1Vhr8CuqIAjOFyXe6JrZVeFYW/CHs5ZxiEd/2wDju3fS7EcgPGJa6z+e4wMj/c2zsC1MwmQhm545tWArpeCwMM3EWoX40D8tC7vjBH5hRmJBmkLp72eJs3KxHThDoK97OZZ2Tp9q5g6blR+V+ex8c8reTBcEBviQ6LaxPGScRNa5HyFrkwmFtdjKh09yEvnOwUIUzi72mTneMgCwcDCx4Ks4GJ63mloXe6st28+tLqcNauYJaJXdQW/HhrPysa/hz23w4/MYuCkS/Y78rgqHNR/Rd5wz/btJzN9RG7dBUfbsifMMaTRSJMzUP6qQ7r1NVjQgpQBAUGSMmvM23+4=
  - secure: E0hdKNfmmdvuDB8iQ0ghXTCNIfZl56ZlJQVw6PHaYVInfCK6SurDtgwbn1ob5advToz3JBHiN6xGJW9y3SQdk//m+D74rkFMNCoU36OnEmgsb/mStAs7DOfQcblmimZfv/zuLGZZrmNxMfNsPxZxxVRQGc0T0lNOxaS8L3vxXbj4MUKpFB/IP61UxHbDJZmPjJ3C7t0RN+Ai+BnhHLGuesfqsC/FFXF49itXcOIqFiwahxqBxYepbB7gDCsSX+L2LhleMC+0Qugfs0Lfnkg4VAOT9MZrMrcThyT5SbmpXLR7H+Xi79t1YPEcz7WsG6YkxCRFRliaiHaMdmPiUqg6BHMYbZaX7L8lyVFA8nXTgwCbRWkRDqAoxpkdT7FlmYV/sx1TiX9r2SSSiQLt/kYC3FZj/8zXMRwoTuklycIYA2rrvq8233SWQEcjpH4WL1NnGnDhsVVpjTxyCSacprbrcWBo0wLEP3jVq3O/gAH8Sd0/MDDgxJRz6lvt+JjR5IsHAAPSNQRTQ/ut/Vwm86TtSX3FEbHPG4Lhnd0m6a3CRmKCnfX47EOeh2bLpULWk8hZOKomeP+Qps54R5zj3bUTh86auivNPNDk6X5bpxnvafNRWLcqRat4mEMeVv4RcNsTkB+b6isO+SBy9ZRkSy3CCiYOxmNuiVYbcqBBaU2QRe8=
before_install:
- gem install travis -v 1.8.5 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=34.209.148.131
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
