language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - jhh@easedot.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: Yu1x62tSrVAXeL8SO0KNVeyHZlKyJ3zjqhVRKwlrK1rZCy3peyh3LEbKX/eo9mSwLSq3N6NMsv2EI85NNGZaqWJX3rzi7PZznoV53C28fbn0/35F/dWtPJwd4qtHd/lxtCwIPJi/DcUiEM4Cd+wg1hV7aObQPBmN8uQPTx09BbfO2HV5OgB2H4hQW5XCXDHY2BuIOuJvjCEEOa3RlybA+4NlHmASap+IOA1efDHdxQ483h7Mu1D27sdw/xwoy1kANpiVEJGfza74KXInYrGlVN1y8CCJ943hgWET1YAOnrvwQn8aT7rCaJGHHp7GSpbswUQ3T2oEp4rAGxt+CkhcfLCOBiQnxNj4RsKHV1IZPFxsbvstXY4KRNeeoSAX6VfzmzGvpWh1ia1/ttslQpZ9fPCuhiFWtizykYnBGoKkpPGCZiREV5Hu46JAL07aBeVpK4N1j9zdywVWJmceAjnm1LB01iUcG0eGEhdkRkBL1NqLwyVgLW/uul3qQ5vziaWW8kmD2EAXwsB3pFtNJWLvcrR3Ph8CQo4r3ESZUcFx3XJ2KCmXwKoUMN6j1qUhtUg6nf0VqcdjOExD0sroR1oFCa5SVqx/UVLoQhePhYjjpMUSbSMOqrB8a85sRC1T1ldquUkIdbOtR2fhk9w4GwGcs6f74zC6PHKHXz6SNB4S1VU=
  - secure: OdHMXEpG1B1ERod1dkyHL7lzmmw7PI3JL7oLZcBpNWwVkLcMWdAkcx0Ws01hS6yC5mGKPT5B6fdfSD9o1QWji7cYMjTgwT5G25cR+8lnmPDDXJjKHU9PWfMo4YiS13QYDqrgcfnPWyrefW6rb3S8NnB0872m8+ktJMmMu2ONexe02L4yB7MM1Gdyq0gD8FTaM5f2lubxaW8BthI1b075Ax6ITApYmxmQZ3L7k+xtfSJ1Oofv7/SGvaoXuf6Ijb89vWJpNCqmZrWRmEgkXhBnEig3GxmTiGH+O01eLeK6ld/IQONE+Ia9IAFS4R7IWR428xDMZOCaiiGP5ITJxowFHoRk/NtPEASMvGoaIBe6C7azjtn/GIokmzWZYmBXSoLm5kLMv06MmDVUcvnXrQmRbfi2putwh8JvjSAGiUvJe0gRbtYmgnoREnbp7YXGCxnZKxxmMC/J3/wQq86X09/TBt+Oto0Jc78UMokpH7yzBWUT/+bd2z8OPy7IN2eGLas4ZaGmEv843e7n2vaQsKKgiYN+Td2dFfNALIoTf99otfxGvJsiCjnj1WWMGVSKkpk60fxmtjWy0NvPNYej9GHhiU/Io+mPFQqRi797KkNq1MQ7BSRWsk8fHedvxs5TZDCAqWBxmRWrxQaDVoOwq8R4WZrhxs1axmIfB8Oi9GmPvz4=
  - secure: k0u49goUopmf+EusAbluB6c7NyHFZ00fJImpvWzKaTQkpxuLdeXiWuZY9YkfrKFlVajaoqYtZ1ohMhfngL53RrM2PtF7//XCFXgzhwi/PgT44KRTTMW6UVLwqh89PAGVym/4BJxasUa1niq4qPbMNAdfAgx88RzZEZX5C/33tXqvIJdeqAIeyTwP9rc/+QfLpuClszvZXrKbdl3k1sW/CsFS5fxigLsvyfcRS6I+ZCDe0Rb6ZspNp6/w9Is2bgC0SRm01Myr+n/Nd05ztqNs5A4wM5c5ofd4cNgdGO649VmfV3vgllVM2CB2vPAEHPg5OydoLjHjDWBvPuPjZg+b2a9u0DzJhXsdqBNRQcSeW3mDYkir8/VSDrW+CeOOnNFzptLIjh1iWmPho1GiRsF+n2oY3I3NdR2ZK3lBHBm6hXbDZsJjBpMblMfF1QQuXhdy18u6Tjgz2wx5nTduXTXrmVBqKe+FktdwtSZk+9uDYWWel5SL7L5s8yvA9ZI4LOGrvZjlpsVVpY8wqf1JJ5wCs98ES4o8g4nXK7k2EOTANbDVaEdjbTVmUAb4irhLwhcRY+WGDCbaTSN3XukdiJkJu8Jp5sl2c4pKKifgEV0cj+OBMk39ES+FDwht57z14he8vcTSeMFJh1X4qpWQbZnUEHaVyyzSB9Kzx1qN+Crzs5k=
  - secure: qh5oqtgj3oU1iHvZ+vB3cIkpsL/XyU7bjyVhfW6EO6pet4d8devihYq9TnXdwaMbRNlVMoQ/kruZI1mLCnGKbBmxYrixa7bH9UXB+S6WxdP0suNx08XF+m7yFw1ID0iNnyb9CRqwVY/VvWjuivkGssrQqHyYFeqHReYXHz83AarhbmVTQX4OG1Mk3vqASvf9ZdH9stbA+zmWfnHJaIGiKdlk8mDIvR44jObC//XaRX7TzJ6xbB0U2iC1O6IUKNLIu+hJvNJn7CBIHK4jp/gX8yuiHqayvliik/7JDoSklcINPyDXSF+uPWzokxiPKqOOYJaYtLNul8X8LYT4wF2U1R1Md9fSpaoaqmyr9YwsDfHen4WbfM/borATX3/1GU+0cZuM1ISejdgSAdlwuV+7MmQ+GQsxsOOOwxHW5TaG4epIzUd/Tg/zjrCWy/1XIGAYgfetpZmWZqR9REaDiHcQ1alqte5ivgi93CBocVS5OjsUtVfBRH2Td2oCjaiBN+emS1iy4DFHgvJTvsulp7kx3s/DDkrACZX1tgeRm6fsugQbRM7es0vGSxa/D2wCfGfXkPNhQzfS38BVw2vCKYio7FnfNDq00u23cf5dHWWWGnkgEVTD0v2svkSqD4Fdss+5Qsol+JqsqJ+zOLBuHrGiWrCC0LVDlTrrGU77XmXFRxc=
  - secure: WaM208FMfiqM84MLk3P5IIOW7zmXxjOGLoRMdf4EmVso5sfX/J1wsiqdsHpyygTjSLtAS2IW6N7Mh/y/Bb20oS+S6QDCcdB3MFxwBP4GFtm7BgOnpwibS8KkfswGcBtLmlbsF026fhZ8n3PjSznifElPElMIqzQr7kAXmwy4BGl4pD3NlER8gthgK+PjOsUVKR68SdLZIiN7aApB0+G+HIrNbMcky2yNga7h8u2Ad3IAXPHExp7o4tMk31r0zfjzamxBRF2w/A79eIR4Cdo6bh9EUHRWN0wSUF4HpQ87ziLuTwuG+HijEjKQIbkrGk9KgIX7Vka46PrF2u3lmeXM4+Ts9Pa9Mp4q06J5pIE4R9ZqRC2olyhRsqiTserbFAdz84aHmTyF/i+N5O3LdmjOj6yMj8W2bheKgDjWNHjoPZpyQFjGmy98VX8vJcHUenRqHmR36hfTPfCyFexmt6P9uB97mFiwilxUwy3ZrND3JIfGwG+Mj55y2fOBL+K5xAOpAP40SZw5h6SHxxX/IJnmO/ER34mzRkp6cDEXbxUrSKn5UCf9FrWkM/XPZxsVqOvDponOU82K3TJXsy8S9LIUcj7P/JfWWabri/52k47S9g5HWsGlh69wGyaPrJ/itnEWg6OulfYNe/TzGkb0MZol4w0nI3dVeiS400tUB9BrOkY=
before_install:
- gem install travis -v 1.8.5 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=34.209.148.131
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
